### ISSUE TITLE
Assertion 'length' failed at pulsecore/memblock.c:218, function pa_memblock_new()

### ISSUE THREAD

**Issue by benpicco** [hfujita/pulseaudio-raop2#23]
I've compiled the latest hf/raop2-v2 branch and after a while, pulseaudio always crashes when streaming to an Android device (Airplayer)

```
E: [raop-sink-[160.45.202.86]:5927] memblock.c: Assertion 'length' failed at pulsecore/memblock.c:218, function pa_memblock_new(). Aborting.
[1]    4549 abort (core dumped)  ./src/pulseaudio -n -F src/default.pa -p $(pwd)/src/
```

**Comment by hfujita** [comment]
Thank you for reporting. However I could reproduce the issue with Ubuntu 14.04, VLC, and Airplayer on Nexus 4. What software did you use on the sender side?

**Comment by benpicco** [comment]
I'm using Clementine, but this also happens with Firefox/Alsa plug-in.
The issue seems to be only occurring with an unstable wifi connection/packet loss.

**Comment by hfujita** [comment]
Okay, I confirmed the issue.
So far I figured out that the crash happened when a packet retransmission occurs around sequence number == 65535.

The code path for crash is as follows:
resend_udp_audio_packets()
  -> pa_raop_packet_buffer_get(c->pbuf, seq + i, 0) [1](https://github.com/hfujita/pulseaudio-raop2/blob/hf/raop2-v2/src/modules/raop/raop-client.c#L511)
    -> pa_memblock_new(pb->mempool, size); // where size==0 [2](https://github.com/hfujita/pulseaudio-raop2/blob/hf/raop2-v2/src/modules/raop/raop-packet-buffer.c#L126)

Now I'm asking the original author who wrote the patch around this code path to figure out the original intention behind the current implementation.

**Comment by hfujita** [comment]
We think we fixed the issue with a few patches, and pushed them into the `hf/raop2-v2-v5.99.1` branch. I'd apperiate it if you could try it out!

**Comment by rainerda** [comment]
thanks for the work. i will try it out as soon as i can fit in some quality time with my stereo and write you back.

**Comment by rainerda** [comment]
Hello! I could repeat the things that led to the bug and instead of crashing it did this:
.........
(3511.798|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4301
(3511.798|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.798|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4302
(3511.802|   0.004) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4311
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4312
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4313
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.802|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4314
(3511.807|   0.004) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.807|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4315
(3511.807|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.807|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4316
(3511.809|   0.001) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(3511.809|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 1 packets starting at 4319

which is perfectly what it should do I would say. No crash after a good two hours playback with streaming flacs to my musicbox with clementine. I will continue using it and report stuff. Thanks!

**Comment by benpicco** [comment]
Thanks a lot, works pretty much flawless now! :+1: 

I really hope you can get it integrated into mainline PA
